
project:
  type: website
  render:
    - "pages/*.qmd"
css: publish/style.css

website:
  title: "QCPU"
  navbar:
    left:
      - pages/index.qmd
      - pages/layout.qmd

format:
  html:
    minimal: true
    page-layout: article
    theme:
      light: yeti
      dark: cyborg
