
project:
  type: website
  render:
    - "pages/*.qmd"
    - "guide/*.qmd"

website:
  title: "QCPU"
  search: true
  navbar:
    left:
      - pages/index.qmd
      - pages/cli.qmd
    right:
      - text: Guide
        href: guide/index.qmd
      - text: Snippets
        href: snippets
      - icon: github
        href: https://github.com/QSmally/QCPU

format:
  html:
    code-copy: true
    minimal: true
    page-layout: article
    number-sections: true
    theme:
      light: yeti
      dark: cyborg
    css: publish/style.css
    bibliography: publish/references.bib
    csl: https://www.zotero.org/styles/ieee-control-systems
