
version: "3.5"

services:
  qcpu-qsmally-org:
    restart: always
    build:
      context: .
      args:
        TAG: "v1.3.450"
    container_name: qcpu-qsmally-org
    image: qcpu-qsmally-org
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./:/Content"
    environment:
      - VIRTUAL_HOST=qcpu.qsmally.org
      - VIRTUAL_NETWORK=nginx
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=qcpu.qsmally.org
      - LETSENCRYPT_EMAIL=info@qbot.eu
    networks:
      - default
      - qcpu-network-bridge
    # ports:
    #   - 80:80

networks:
  qcpu-network-bridge:
    name: qcpu-network-bridge
