
version: "3"

services:
  qcpu-documentation:
    restart: always
    build: .
    container_name: qcpu-documentation
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./:/Content"
    ports:
      - 80:80
